modLoader = "javafml" #mandatory
loaderVersion = "[40,)" #mandatory
license = "MIT"
issueTrackerURL="https://github.com/devOS-Sanity-Edition/DudeWhatsMyGePeUwu/issues" #optional
logoFile="logo.png"

[[mods]] #mandatory
modId = "dudewhatsmygepeuwu" #mandatory
version = "1.0.0" #mandatory
displayName = "Dude, What's My GePeUWU?" #mandatory
displayURL="https://github.com/devOS-Sanity-Edition/DudeWhatsMyGePeUwu" #optional
 #optional
credits="Stereo528, asoji"
authors = "devOS-Nautical"
description = '''
A mod that tells what GPU you're using for Minecraft from the title screen and in your logs, thus letting you avoid the annoyance that is loading into a world and pressing f3 to find out what your GPU is.

Can be very useful if you have a dual GPU laptop or tower and trying to figure out what GPU is your Minecraft using!
'''